variables:
  GOPATH: '$CI_PROJECT_DIR/.cache/go'

stages:
  - build
  - test

clientBuild:
  stage: build
  tags:
    - node
  script:
    - cd web/
    - npm install
    - npm run build

serverBuild:
  stage: build
  tags:
    - golang
  script:
    - mkdir -p .cache/go
    - cd cmd/
    - go build ./...
  cache:
    key: ${CI_BUILD_REF_NAME}
    paths:
      - .cache/go
  artifacts:
    paths:
      - .cache/go

memoryDatabase:
  stage: test
  tags:
    - golang
  script:
    - cd internal/database/memory
    - go test -v

internalUtil:
  stage: test
  tags:
    - golang
  script:
    - cd internal/util
    - go test -v

pkgPassentropy:
  stage: test
  tags:
    - golang
  script:
    - cd pkg/passentropy
    - go test -v

databaseTypes:
  stage: test
  tags:
    - golang
  script:
    - cd internal/database/
    - go test -v

fileProcessing:
  stage: test
  tags:
    - golang
  services:
    - name: lexpredict/tika-server:latest
      alias: tika
  variables:
    TIKA_PATH: http://tika:9998
  script:
    - cd internal/database/process
    - go test -v
