stages:
  - build
  - test

build:
  stage: build
  tags:
    - node
  script:
    - cd web/
    - npm install
    - npm run build

memoryDatabase:
  stage: test
  tags:
    - golang
  script:
    - cd internal/database/memory
    - go test
