version: '3'
services:
  server:
    build:
      context: .
      dockerfile: ./cmd/knaxim/Dockerfile
    restart: "unless-stopped"
    ports:
      - "8005:80"
    expose:
      - "80"
    volumes:
    # These are static files located on the host machine.
      - web:/srv
    depends_on:
      - mongo
      - tika
      - gotenberg
    networks:
      - app-plane
    environment:
      - KNAXIMINIT=restart
  mongo:
    image: mongo:latest
    restart: "unless-stopped"
    ports:
      - "27017:27017"
    networks:
      - app-plane
    volumes:
      - /var/lib/mongodb/db:/data/db
      - /var/lib/mongodb/configdb:/data/configdb
  tika:
    image: lexpredict/tika-server:latest
    restart: "unless-stopped"
    # Warning !!! port is mapped to host for Testing only!
    ports:
      - "9998:9998"
    networks:
      - app-plane
  gotenberg:
    # May need to scale: https://thecodingmachine.github.io/gotenberg/#scalability.strategies.scaling
    image: thecodingmachine/gotenberg:latest # Should version be latest or 6?
    restart: "unless-stopped"
    # Is port entry needed?
    ports:
      - "3000:3000"
    networks:
      - app-plane
    environment:
      - DEFAULT_WAIT_TIMEOUT=240
      - MAXIMUM_WAIT_TIMEOUT=240
  frontend:
    restart: on-failure:5
    ports:
      - "80:8080"
    build:
      context: ./web
    env_file: .env.prod
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/nginx-proxy.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - server
    networks:
      - app-plane 


volumes:
  web:
  mongo:
  mongo-cfg:
networks:
  app-plane:
