version: '3'
services:
  server:
    build: .
    restart: "unless-stopped"
    ports:
      - "8005:80"
    volumes:
    # These are static files located on the host machine.
      - web:/public
    depends_on:
      - mongo
      - tika
      - gotenberg
    networks:
      - app-plane
    environment:
      - KNAXIMINIT
  mongo:
    image: mongo:latest
    # Warning !!! port is mapped to host for Testing only!
    ports:
      - "27017:27017"
    networks:
      - app-plane
    volumes:
      - mongo:/data/db
      - mongo-cfg:/data/configdb
  tika:
    image: lexpredict/tika-server:latest
    # Warning !!! port is mapped to host for Testing only!
    ports:
      - "9998:9998"
    networks:
      - app-plane
  gotenberg:
    # May need to scale: https://thecodingmachine.github.io/gotenberg/#scalability.strategies.scaling
    image: thecodingmachine/gotenberg:latest # Should version be latest or 6?
    # Is port entry needed?
    ports:
      - "3000:3000"
    networks:
      - app-plane
    environment:
      - DEFAULT_WAIT_TIMEOUT=240
      - MAXIMUM_WAIT_TIMEOUT=240

volumes:
  web:
  mongo:
  mongo-cfg:
networks:
  app-plane:
